[package]
name = "actix-storage-sled"
version = "0.1.2"
authors = ["Pouya M. B. <pooyamb@gmail.com>"]
description = "An implementation of actix-storage based on sled"
edition = "2018"
readme = "README.md"
repository = "https://github.com/pooyamb/actix-storage/"
documentation = "https://docs.rs/actix-storage-sled"
license = "MIT OR Apache-2.0"
keywords = ["actix", "storage", "web", "async", "sled"]
categories = ["asynchronous", "caching", "web-programming::http-server"]

[package.metadata.docs.rs]
features = ["actor"]

[dependencies]
actix = { version = "0.10", default-features = false }
async-trait = "0.1"
thiserror = "1"
sled = "0.34"
delay-queue = { version = "0.2", optional = true }
zerocopy = { version = "0.3", optional = true }
byteorder = { version = "1.3", optional = true }
actix-storage = { version = "0.1.2", features = ["with-serde"] }

[dev-dependencies]
actix-web = "3"
actix-rt = "1.1"
rand = "0.7"
serde = "1"
actix-storage = { version = "0.1.2", features = ["all", "tests"] }

[features]
actor = ["delay-queue", "zerocopy", "byteorder"]
compression = ["sled/compression"]
