[package]
name = "actix-storage"
version = "0.2.0-alpha.1"
authors = ["Pouya M. B. <pooyamb@gmail.com>"]
description = "General key value storage for actix-web"
edition = "2018"
readme = "README.md"
repository = "https://github.com/pooyamb/actix-storage/"
documentation = "https://docs.rs/actix-storage"
license = "MIT OR Apache-2.0"
keywords = ["actix", "storage", "web", "async"]
categories = ["asynchronous", "caching", "web-programming::http-server"]

[dependencies]
actix = { version = "0.10", default-features = false }
actix-web = { version = "3", default-features = false }
log = "0.4"
async-trait = "0.1"
thiserror = "1"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
serde_cbor = { version = "0.11", optional = true }
serde_yaml = { version = "0.8", optional = true }
bincode = { version = "1.3", optional = true }
ron = { version = "0.6", optional = true }
quick-xml = { version = "0.22", features = ["serialize"], optional = true }
# For tests
actix-rt = { version= "1.1", optional= true }
futures = { version= "0.3", optional= true }

[dev-dependencies]
actix-rt = "1.1"

[features]
all = [
    "serde-json",
    "serde-cbor",
    "serde-yaml",
    "serde-bincode",
    "serde-ron",
    "serde-xml"
]
serde-json = ["with-serde", "serde_json"]
serde-cbor = ["with-serde", "serde_cbor"]
serde-yaml = ["with-serde", "serde_yaml"]
serde-bincode = ["with-serde", "bincode"]
serde-ron = ["with-serde", "ron"]
serde-xml = ["with-serde", "quick-xml"]
with-serde = ["serde"]
tests = ["actix-rt", "futures"]

[package.metadata.docs.rs]
features = ["all"]
