name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-20.04
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: sudo apt install redis-server -y
      - run: sudo service redis-server start

      - uses: actions-rs/tarpaulin@v0.1.0
        with:
          args: --all-features --workspace -o Xml -- --test-threads=2

      - uses: codecov/codecov-action@v1.0.14
